### ISSUE TITLE
Roadmap to merging the waveform branch

### ISSUE THREAD

**Issue by Cody-G** [HolyLab/Imagine#36]
- [x] Process analog entries in the .json command file as raw values.  With our DAQs this means that they should be ~~UInt16 values (0...2^16-1)~~ Int16 values (-2^15...2^15-1).  These values will then be scaled by Imagine to a ~~0-10V~~ -10-10V range before writing them to the analog output channels.
- [x] Add any important untracked files to the git repo (there is at least one ui_ file missing)
- [x] Make sure that we are recording reserved input channels (camera and positioner).  Eventually we'd like to allow recording from extra user-specified channels and to save the camera signals in a ".di" file as UInt8 values (1 or 0 to indicate true or false).  However I think we're safe to merge this before that's ready.  That can come in a later pull request. 
- [x] Improve handling of redundant GUI entries when waveform mode is enabled.  We thought about graying-out these entries.  However I see one potential problem with this.  When positioning the sample, users typically run "live" mode before doing a recording.  They may also run live mode between recordings.  Live mode takes its exposure time parameter from the GUI.  I think we should continue to allow setting the exposure time for live mode from the GUI, and that should remain independent from the .json exposure time.  Maybe we could pop up a dialog box when the user enables waveform mode?  The box could give a warning like "Recording in waveform mode will override any camera or positioner settings that you set in the camera or positioner tabs.  However the behavior of "live" mode does not change: the exposure time is taken from the camera tab."
- [x] Set the PCO camera trigger mode when waveform mode is enabled.  ~~After some discussion I think we've agreed to use "exposure control" mode rather than "exposure start" mode, which means the TTL pulse will determine the exact timing of both the start and stop of exposure.~~ **Nevermind, we will just support both modes!**  After reading the SDK manual I see that we specifically want to use "fast external exposure control" mode.  See the manual entries for PCO_GetTriggerMode and PCO_SetTriggerMode, pages 100-101
- [x] Update the PCO SDK to make sure that the above change is effective.
- [x] Polish up the `ImagineInterface` Julia package (Cody) **PR: https://github.com/HolyLab/ImagineInterface/pull/20**
    - [x] Change raw type of analog output channels to `Int16`
    - [x] Enforce that users cannot write negative voltages to piezo analog output channels
- [x] Do some unidirectional and bidirectional test recordings to make sure everything works okay (Cody)

Not necessary for merging, but let's do this anyway:
- [ ] Remove large files that are currently untracked from the git history (we have some old binary files and some libraries taking up lots of space, currently the repo is well over 100MB)
